name: makezip

on:
  push:
    branches: [ main ]
    paths:
      - server/**
    
  workflow_dispatch:

jobs:
  makezip:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
       
      - name: release server
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.funnytoken }}"
          automatic_release_tag: latest
          files: |
            server
