name: makezip

on:
  push:
    branches: [ main ]
    paths:
      - server/**
    
  workflow_dispatch:

jobs:
  makezip:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
       
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            server
